### PR TITLE
Merge with bublejs-brunch

### PR DESCRIPTION
**Pull request by denysdovhan**
There are two plugins for [Buble](https://buble.surge.sh):

* [buble-brunch]
* [bublejs-brunch]

 That causes confusions between them. The first one has better name on NPM, however, the second one has better implementation. This PR merges [buble-brunch] and [bublejs-brunch].

@roperzh you need to do this:

1. Check this PR if everything is OK
2. Merge this PR.
3. Give @aMarCruz permissions for this repo and NPM permissions for this package.
4. Publish a new `5.0.0` version.

Also, @aMarCruz, please, notice that bublejs-brunch should be deprecated. I'm going to open a PR for that reason.

**P.S:** Would be great if this plugin will be moved to the Brunch repo where we can take care of it, but that's completely up to you ;)

**UPD:** https://github.com/aMarCruz/bublejs-brunch/pull/1 — PR that deprecates [bublejs-brunch].

[buble-brunch]: https://github.com/roperzh/buble-brunch
[bublejs-brunch]: https://github.com/aMarCruz/bublejs-brunch

### CODE REVIEW

**Comment by roperzh** [comment]
Hey @denysdovhan !

Thanks so much for taking the lead on this :). Everything looks good, I'll merge it ASAP.

> P.S: Would be great if this plugin will be moved to the Brunch repo where we can take care of it, but that's completely up to you ;)

Sounds good to me! by doing this, do I still have to give @aMarCruz permissions to this repo?

I know it's a dumb question, but I'm trying to figure out the best workflow.

**Comment by denysdovhan** [comment]
If you are ready to migrate this repo to the Brunch organization, then do following:

1. Merge this PR.
1. Add @aMarCruz to this repo.
1. Transfer ownership to the Brunch using GitHub repo settings.
1. Give a permissions on NPM for @paulmillr.

**Comment by aMarCruz** [comment]
@denysdovhan , @roperzh , I agree.

I made bublejs-brunch to cover particular needs of my team, specifically support for source maps.
My plugin embeds a hacked copy of Bublé because issues [reported here](https://gitlab.com/Rich-Harris/buble/issues/136), but this is solved in Bublé v0.15.2

@denysdovhan , you PR is right except in [this line](https://github.com/roperzh/buble-brunch/pull/4/commits/1481b8e2ae672fecdf50e5dd8c4a3d40bd93f1aa#diff-168726dbe96b3ce427e7fedce31bb0bcR33) of index.js:

```js
const result = flatten(file, output.code);
```
must be changed to:
```js
const result = flatten(file, output.code, sourcemaps);
```

I will update my repo asap.
Great work!

**Comment by denysdovhan** [comment]
@aMarCruz it's fixed in https://github.com/roperzh/buble-brunch/pull/4/commits/e14b49af97070530a63f178ca2f5630f5a54542c.

**Comment by aMarCruz** [comment]
@denysdovhan thanks!

**Pull request merged**
